<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "al_gemeinwohlpruefung"
 *
 * Auto generated by Extension Builder 2018-01-15
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Render Pdf',
    'description' => 'Render Pdf using fPdf und fPdi ',
    'category' => 'plugin',
    'author' => 'Wolfgang Bertl',
    'author_email' => 'wolfgang.bertl@almitra.biz',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '1',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.1.1',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-11.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
